version: '3.8'

services:
  web:
    build: .
    env_file:
      - ./app/.env
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/src/app
    command: go run cmd/main/app.go
    depends_on:
      - db
  db:
    restart: always
    image: postgres:alpine
    environment:
      - POSTGRES_USER=konstantin
      - POSTGRES_PASSWORD=task12345
      - POSTGRES_DB=practice_task_db
    ports:
      - "3300:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db: